id = "yql"
name = "YQL"
version = "0.0.1"
schema_version = 1
authors = ["Ivan Udovin"]
description = "YTsaurus YQL query language support for Zed"
repository = "https://github.com/udovin/zed-yql"

[grammars.yql]
repository = "https://github.com/udovin/tree-sitter-yql"
rev = "5b596ef48ea6aaaea324b7279bf098331aac8135"
