id = "yql"
name = "YQL"
version = "0.0.1"
schema_version = 1
authors = ["Ivan Udovin"]
description = "YTsaurus YQL query language support for Zed"
repository = "https://github.com/udovin/zed-yql"

[grammars.yql]
repository = "https://github.com/udovin/tree-sitter-yql"
rev = "7e8d3e1eaf0c28f74732576c55caefb580c4c875"
