name = "YQL"
grammar = "yql"
path_suffixes = ["yql"]
line_comments = ["-- "]
block_comments = [{ start = "/* ", end = " */" }]
tab_size = 4
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "(", end = ")", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "{", end = "}", close = true, newline = true },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "`", end = "`", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "/*", end = " */", close = true, newline = false, not_in = ["string", "comment"] },
]

word_characters = ["$"]
